-- study-fine 초기 스키마: 스터디룸(단일 행) + 멤버 + 회차 + 출석 기록
-- DATA-MODEL.md §2·§3 그대로. 컬럼/제약/인덱스 변경 시 새 버전 파일을 추가할 것(이 파일은 수정 금지).

CREATE TABLE study_room (
    id                  BIGINT PRIMARY KEY,
    name                VARCHAR(60)    NOT NULL,
    late_fine_amount    INTEGER        NOT NULL CHECK (late_fine_amount >= 0),
    absent_fine_amount  INTEGER        NOT NULL CHECK (absent_fine_amount >= 0),
    created_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT chk_study_room_singleton CHECK (id = 1)
);

CREATE TABLE member (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255)   NOT NULL,
    password_hash   VARCHAR(72)    NOT NULL,
    name            VARCHAR(50)    NOT NULL,
    role            VARCHAR(20)    NOT NULL CHECK (role IN ('ORGANIZER', 'MEMBER')),
    active          BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_member_email ON member (email);

CREATE TABLE study_session (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_date    DATE            NOT NULL,
    title           VARCHAR(100)    NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_study_session_date ON study_session (session_date);

CREATE TABLE attendance_record (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      BIGINT          NOT NULL REFERENCES study_session (id) ON DELETE CASCADE,
    member_id       BIGINT          NOT NULL REFERENCES member (id) ON DELETE RESTRICT,
    status          VARCHAR(10)     NOT NULL CHECK (status IN ('PRESENT', 'LATE', 'ABSENT')),
    fine_amount     INTEGER         NOT NULL CHECK (fine_amount >= 0),
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT now()
);

-- 한 회차에 한 멤버는 1건. bulk upsert 재저장 시 중복 방지의 최종 방어선이자 회차별 조회 인덱스.
CREATE UNIQUE INDEX uq_attendance_session_member ON attendance_record (session_id, member_id);

-- 복합 유니크는 선두 컬럼(session_id)부터만 유효하므로 member_id 단독 필터링(누적 벌금 집계, 내 출석 내역)엔 못 쓴다.
CREATE INDEX ix_attendance_member ON attendance_record (member_id);

-- 벌금 단가는 하드코딩이 아니라 운영자가 런타임에 바꿀 수 있어야 하므로 설정 테이블에 둔다.
-- 앱 기동 시 항상 존재해야 하는 설정 행이므로 데모 시드가 아니라 스키마의 일부로 취급한다.
INSERT INTO study_room (id, name, late_fine_amount, absent_fine_amount)
VALUES (1, '스터디룸', 3000, 5000);
